//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.296
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.296.
// 
#pragma warning disable 1591

namespace Proyecto.MenPas {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WS_EstimacionFSoap", Namespace="http://tempuri.org/")]
    public partial class WS_EstimacionF : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback EstaRegistradoOperationCompleted;
        
        private System.Threading.SendOrPostCallback dame_perfilOperationCompleted;
        
        private System.Threading.SendOrPostCallback Obtener_grupoOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertarFuncionOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertarPuntoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerFuncionesOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerPuntosOperationCompleted;
        
        private System.Threading.SendOrPostCallback BorrarFuncionOperationCompleted;
        
        private System.Threading.SendOrPostCallback BorrarPuntoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerFuncionesDSOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerPuntosDSOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WS_EstimacionF() {
            this.Url = global::Proyecto.Properties.Settings.Default.Estimación_de_funciones_MenPas_WS_EstimacionF;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event EstaRegistradoCompletedEventHandler EstaRegistradoCompleted;
        
        /// <remarks/>
        public event dame_perfilCompletedEventHandler dame_perfilCompleted;
        
        /// <remarks/>
        public event Obtener_grupoCompletedEventHandler Obtener_grupoCompleted;
        
        /// <remarks/>
        public event InsertarFuncionCompletedEventHandler InsertarFuncionCompleted;
        
        /// <remarks/>
        public event InsertarPuntoCompletedEventHandler InsertarPuntoCompleted;
        
        /// <remarks/>
        public event ObtenerFuncionesCompletedEventHandler ObtenerFuncionesCompleted;
        
        /// <remarks/>
        public event ObtenerPuntosCompletedEventHandler ObtenerPuntosCompleted;
        
        /// <remarks/>
        public event BorrarFuncionCompletedEventHandler BorrarFuncionCompleted;
        
        /// <remarks/>
        public event BorrarPuntoCompletedEventHandler BorrarPuntoCompleted;
        
        /// <remarks/>
        public event ObtenerFuncionesDSCompletedEventHandler ObtenerFuncionesDSCompleted;
        
        /// <remarks/>
        public event ObtenerPuntosDSCompletedEventHandler ObtenerPuntosDSCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EstaRegistrado", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool EstaRegistrado(string usuario, string contraseña) {
            object[] results = this.Invoke("EstaRegistrado", new object[] {
                        usuario,
                        contraseña});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void EstaRegistradoAsync(string usuario, string contraseña) {
            this.EstaRegistradoAsync(usuario, contraseña, null);
        }
        
        /// <remarks/>
        public void EstaRegistradoAsync(string usuario, string contraseña, object userState) {
            if ((this.EstaRegistradoOperationCompleted == null)) {
                this.EstaRegistradoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEstaRegistradoOperationCompleted);
            }
            this.InvokeAsync("EstaRegistrado", new object[] {
                        usuario,
                        contraseña}, this.EstaRegistradoOperationCompleted, userState);
        }
        
        private void OnEstaRegistradoOperationCompleted(object arg) {
            if ((this.EstaRegistradoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EstaRegistradoCompleted(this, new EstaRegistradoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/dame_perfil", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string dame_perfil(string usuario) {
            object[] results = this.Invoke("dame_perfil", new object[] {
                        usuario});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void dame_perfilAsync(string usuario) {
            this.dame_perfilAsync(usuario, null);
        }
        
        /// <remarks/>
        public void dame_perfilAsync(string usuario, object userState) {
            if ((this.dame_perfilOperationCompleted == null)) {
                this.dame_perfilOperationCompleted = new System.Threading.SendOrPostCallback(this.Ondame_perfilOperationCompleted);
            }
            this.InvokeAsync("dame_perfil", new object[] {
                        usuario}, this.dame_perfilOperationCompleted, userState);
        }
        
        private void Ondame_perfilOperationCompleted(object arg) {
            if ((this.dame_perfilCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.dame_perfilCompleted(this, new dame_perfilCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Obtener_grupo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Obtener_grupo(string usuario) {
            object[] results = this.Invoke("Obtener_grupo", new object[] {
                        usuario});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Obtener_grupoAsync(string usuario) {
            this.Obtener_grupoAsync(usuario, null);
        }
        
        /// <remarks/>
        public void Obtener_grupoAsync(string usuario, object userState) {
            if ((this.Obtener_grupoOperationCompleted == null)) {
                this.Obtener_grupoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtener_grupoOperationCompleted);
            }
            this.InvokeAsync("Obtener_grupo", new object[] {
                        usuario}, this.Obtener_grupoOperationCompleted, userState);
        }
        
        private void OnObtener_grupoOperationCompleted(object arg) {
            if ((this.Obtener_grupoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Obtener_grupoCompleted(this, new Obtener_grupoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertarFuncion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool InsertarFuncion(string usuario, string funcion, string hora) {
            object[] results = this.Invoke("InsertarFuncion", new object[] {
                        usuario,
                        funcion,
                        hora});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void InsertarFuncionAsync(string usuario, string funcion, string hora) {
            this.InsertarFuncionAsync(usuario, funcion, hora, null);
        }
        
        /// <remarks/>
        public void InsertarFuncionAsync(string usuario, string funcion, string hora, object userState) {
            if ((this.InsertarFuncionOperationCompleted == null)) {
                this.InsertarFuncionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertarFuncionOperationCompleted);
            }
            this.InvokeAsync("InsertarFuncion", new object[] {
                        usuario,
                        funcion,
                        hora}, this.InsertarFuncionOperationCompleted, userState);
        }
        
        private void OnInsertarFuncionOperationCompleted(object arg) {
            if ((this.InsertarFuncionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertarFuncionCompleted(this, new InsertarFuncionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InsertarPunto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool InsertarPunto(string usuario, double x, double y, string hora) {
            object[] results = this.Invoke("InsertarPunto", new object[] {
                        usuario,
                        x,
                        y,
                        hora});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void InsertarPuntoAsync(string usuario, double x, double y, string hora) {
            this.InsertarPuntoAsync(usuario, x, y, hora, null);
        }
        
        /// <remarks/>
        public void InsertarPuntoAsync(string usuario, double x, double y, string hora, object userState) {
            if ((this.InsertarPuntoOperationCompleted == null)) {
                this.InsertarPuntoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertarPuntoOperationCompleted);
            }
            this.InvokeAsync("InsertarPunto", new object[] {
                        usuario,
                        x,
                        y,
                        hora}, this.InsertarPuntoOperationCompleted, userState);
        }
        
        private void OnInsertarPuntoOperationCompleted(object arg) {
            if ((this.InsertarPuntoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertarPuntoCompleted(this, new InsertarPuntoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerFunciones", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] ObtenerFunciones() {
            object[] results = this.Invoke("ObtenerFunciones", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerFuncionesAsync() {
            this.ObtenerFuncionesAsync(null);
        }
        
        /// <remarks/>
        public void ObtenerFuncionesAsync(object userState) {
            if ((this.ObtenerFuncionesOperationCompleted == null)) {
                this.ObtenerFuncionesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerFuncionesOperationCompleted);
            }
            this.InvokeAsync("ObtenerFunciones", new object[0], this.ObtenerFuncionesOperationCompleted, userState);
        }
        
        private void OnObtenerFuncionesOperationCompleted(object arg) {
            if ((this.ObtenerFuncionesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerFuncionesCompleted(this, new ObtenerFuncionesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerPuntos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] ObtenerPuntos() {
            object[] results = this.Invoke("ObtenerPuntos", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerPuntosAsync() {
            this.ObtenerPuntosAsync(null);
        }
        
        /// <remarks/>
        public void ObtenerPuntosAsync(object userState) {
            if ((this.ObtenerPuntosOperationCompleted == null)) {
                this.ObtenerPuntosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerPuntosOperationCompleted);
            }
            this.InvokeAsync("ObtenerPuntos", new object[0], this.ObtenerPuntosOperationCompleted, userState);
        }
        
        private void OnObtenerPuntosOperationCompleted(object arg) {
            if ((this.ObtenerPuntosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerPuntosCompleted(this, new ObtenerPuntosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BorrarFuncion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool BorrarFuncion(string usuario, string funcion, string hora) {
            object[] results = this.Invoke("BorrarFuncion", new object[] {
                        usuario,
                        funcion,
                        hora});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void BorrarFuncionAsync(string usuario, string funcion, string hora) {
            this.BorrarFuncionAsync(usuario, funcion, hora, null);
        }
        
        /// <remarks/>
        public void BorrarFuncionAsync(string usuario, string funcion, string hora, object userState) {
            if ((this.BorrarFuncionOperationCompleted == null)) {
                this.BorrarFuncionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBorrarFuncionOperationCompleted);
            }
            this.InvokeAsync("BorrarFuncion", new object[] {
                        usuario,
                        funcion,
                        hora}, this.BorrarFuncionOperationCompleted, userState);
        }
        
        private void OnBorrarFuncionOperationCompleted(object arg) {
            if ((this.BorrarFuncionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BorrarFuncionCompleted(this, new BorrarFuncionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BorrarPunto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool BorrarPunto(string usuario, int x, int y, string hora) {
            object[] results = this.Invoke("BorrarPunto", new object[] {
                        usuario,
                        x,
                        y,
                        hora});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void BorrarPuntoAsync(string usuario, int x, int y, string hora) {
            this.BorrarPuntoAsync(usuario, x, y, hora, null);
        }
        
        /// <remarks/>
        public void BorrarPuntoAsync(string usuario, int x, int y, string hora, object userState) {
            if ((this.BorrarPuntoOperationCompleted == null)) {
                this.BorrarPuntoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBorrarPuntoOperationCompleted);
            }
            this.InvokeAsync("BorrarPunto", new object[] {
                        usuario,
                        x,
                        y,
                        hora}, this.BorrarPuntoOperationCompleted, userState);
        }
        
        private void OnBorrarPuntoOperationCompleted(object arg) {
            if ((this.BorrarPuntoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BorrarPuntoCompleted(this, new BorrarPuntoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerFuncionesDS", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ObtenerFuncionesDS() {
            object[] results = this.Invoke("ObtenerFuncionesDS", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerFuncionesDSAsync() {
            this.ObtenerFuncionesDSAsync(null);
        }
        
        /// <remarks/>
        public void ObtenerFuncionesDSAsync(object userState) {
            if ((this.ObtenerFuncionesDSOperationCompleted == null)) {
                this.ObtenerFuncionesDSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerFuncionesDSOperationCompleted);
            }
            this.InvokeAsync("ObtenerFuncionesDS", new object[0], this.ObtenerFuncionesDSOperationCompleted, userState);
        }
        
        private void OnObtenerFuncionesDSOperationCompleted(object arg) {
            if ((this.ObtenerFuncionesDSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerFuncionesDSCompleted(this, new ObtenerFuncionesDSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerPuntosDS", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ObtenerPuntosDS() {
            object[] results = this.Invoke("ObtenerPuntosDS", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerPuntosDSAsync() {
            this.ObtenerPuntosDSAsync(null);
        }
        
        /// <remarks/>
        public void ObtenerPuntosDSAsync(object userState) {
            if ((this.ObtenerPuntosDSOperationCompleted == null)) {
                this.ObtenerPuntosDSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerPuntosDSOperationCompleted);
            }
            this.InvokeAsync("ObtenerPuntosDS", new object[0], this.ObtenerPuntosDSOperationCompleted, userState);
        }
        
        private void OnObtenerPuntosDSOperationCompleted(object arg) {
            if ((this.ObtenerPuntosDSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerPuntosDSCompleted(this, new ObtenerPuntosDSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void EstaRegistradoCompletedEventHandler(object sender, EstaRegistradoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EstaRegistradoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EstaRegistradoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void dame_perfilCompletedEventHandler(object sender, dame_perfilCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class dame_perfilCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal dame_perfilCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void Obtener_grupoCompletedEventHandler(object sender, Obtener_grupoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Obtener_grupoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Obtener_grupoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void InsertarFuncionCompletedEventHandler(object sender, InsertarFuncionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertarFuncionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertarFuncionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void InsertarPuntoCompletedEventHandler(object sender, InsertarPuntoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertarPuntoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertarPuntoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ObtenerFuncionesCompletedEventHandler(object sender, ObtenerFuncionesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerFuncionesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerFuncionesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ObtenerPuntosCompletedEventHandler(object sender, ObtenerPuntosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerPuntosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerPuntosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void BorrarFuncionCompletedEventHandler(object sender, BorrarFuncionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BorrarFuncionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BorrarFuncionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void BorrarPuntoCompletedEventHandler(object sender, BorrarPuntoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BorrarPuntoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BorrarPuntoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ObtenerFuncionesDSCompletedEventHandler(object sender, ObtenerFuncionesDSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerFuncionesDSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerFuncionesDSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ObtenerPuntosDSCompletedEventHandler(object sender, ObtenerPuntosDSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerPuntosDSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerPuntosDSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591