//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18034
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Traducciones {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Cadenas {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Cadenas() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Traducciones.Cadenas", typeof(Cadenas).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro? Las funciones que actualmente tiene almacenadas se borrarán.
        /// </summary>
        public static string advertenciaCargarHistorialDeFunciones {
            get {
                return ResourceManager.GetString("advertenciaCargarHistorialDeFunciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro? Los puntos que actualmente tiene almacenadas se borrarán.
        /// </summary>
        public static string advertenciaCargarHistorialDePuntos {
            get {
                return ResourceManager.GetString("advertenciaCargarHistorialDePuntos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Advertencia: debido al zoom, no se puede mostrar celdas.
        /// </summary>
        public static string advertenciaCeldasZoom {
            get {
                return ResourceManager.GetString("advertenciaCeldasZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ADVERTENCIA: el coeficiente de regresión ha de.
        /// </summary>
        public static string advertenciaCoeficiente1 {
            get {
                return ResourceManager.GetString("advertenciaCoeficiente1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ser un número entero positivo mayor que 1.
        /// </summary>
        public static string advertenciaCoeficiente2 {
            get {
                return ResourceManager.GetString("advertenciaCoeficiente2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ADVERTENCIA: el factor de desplazamiento ha de ser un.
        /// </summary>
        public static string advertenciaDesplazamiento1 {
            get {
                return ResourceManager.GetString("advertenciaDesplazamiento1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a número entero positivo mayor que cero y múltiplo de 10.
        /// </summary>
        public static string advertenciaDesplazamiento2 {
            get {
                return ResourceManager.GetString("advertenciaDesplazamiento2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ADVERTENCIA: si el valor es igual a 0, el programa.
        /// </summary>
        public static string advertenciaFilas1 {
            get {
                return ResourceManager.GetString("advertenciaFilas1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a parará la importación por cada 10 filas vacías.
        /// </summary>
        public static string advertenciaFilas2 {
            get {
                return ResourceManager.GetString("advertenciaFilas2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ADVERTENCIA: sólo puede ser un número.
        /// </summary>
        public static string advertenciaNumero {
            get {
                return ResourceManager.GetString("advertenciaNumero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Archivo JPG|*.jpg.
        /// </summary>
        public static string archivoJPG {
            get {
                return ResourceManager.GetString("archivoJPG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aumentar zoom.
        /// </summary>
        public static string aumentarZoom {
            get {
                return ResourceManager.GetString("aumentarZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Azul.
        /// </summary>
        public static string azul {
            get {
                return ResourceManager.GetString("azul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Azul oscuro.
        /// </summary>
        public static string azulOscuro {
            get {
                return ResourceManager.GetString("azulOscuro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Borrar funciones seleccionadas.
        /// </summary>
        public static string borrarFunciones {
            get {
                return ResourceManager.GetString("borrarFunciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Borrar primera función del historial.
        /// </summary>
        public static string borrarPrimeraFuncionDelHistorial {
            get {
                return ResourceManager.GetString("borrarPrimeraFuncionDelHistorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Borrar primer punto del historial.
        /// </summary>
        public static string borrarPrimerPuntoDelHistorial {
            get {
                return ResourceManager.GetString("borrarPrimerPuntoDelHistorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Borrar puntos seleccionados.
        /// </summary>
        public static string borrarPuntos {
            get {
                return ResourceManager.GetString("borrarPuntos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Borrar última función del historial.
        /// </summary>
        public static string borrarUltimaFuncionDelHistorial {
            get {
                return ResourceManager.GetString("borrarUltimaFuncionDelHistorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Borrar último punto del historial.
        /// </summary>
        public static string borrarUltimoPuntoDelHistorial {
            get {
                return ResourceManager.GetString("borrarUltimoPuntoDelHistorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargar historial de funciones.
        /// </summary>
        public static string cargarHistorialDeFunciones {
            get {
                return ResourceManager.GetString("cargarHistorialDeFunciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cargar historial de puntos.
        /// </summary>
        public static string cargarHistorialDePuntos {
            get {
                return ResourceManager.GetString("cargarHistorialDePuntos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coeficiente.
        /// </summary>
        public static string coeficiente {
            get {
                return ResourceManager.GetString("coeficiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coeficiente de regresión:.
        /// </summary>
        public static string coeficienteDeRegresion {
            get {
                return ResourceManager.GetString("coeficienteDeRegresion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Color.
        /// </summary>
        public static string color {
            get {
                return ResourceManager.GetString("color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coordenadas.
        /// </summary>
        public static string coordenadas {
            get {
                return ResourceManager.GetString("coordenadas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coordenada X =.
        /// </summary>
        public static string coordenadaX {
            get {
                return ResourceManager.GetString("coordenadaX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Coordenada Y =.
        /// </summary>
        public static string coordenadaY {
            get {
                return ResourceManager.GetString("coordenadaY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Definición estándard.
        /// </summary>
        public static string definicionEstandard {
            get {
                return ResourceManager.GetString("definicionEstandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Definición formal.
        /// </summary>
        public static string definicionFormal {
            get {
                return ResourceManager.GetString("definicionFormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Desplazamiento.
        /// </summary>
        public static string desplazamiento {
            get {
                return ResourceManager.GetString("desplazamiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disminuir zoom.
        /// </summary>
        public static string disminuirZoom {
            get {
                return ResourceManager.GetString("disminuirZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error: el punto ya se encuentra en el historial.
        /// </summary>
        public static string error001 {
            get {
                return ResourceManager.GetString("error001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error: introduzca primero una función.
        /// </summary>
        public static string error002 {
            get {
                return ResourceManager.GetString("error002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error: la función se encuentra en el historial.
        /// </summary>
        public static string error003 {
            get {
                return ResourceManager.GetString("error003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error: tiene que haber al menos dos puntos en el panel.
        /// </summary>
        public static string error004 {
            get {
                return ResourceManager.GetString("error004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error: seleccione antes un tipo de aproximación.
        /// </summary>
        public static string error005 {
            get {
                return ResourceManager.GetString("error005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error: no se ha elegido ningún color.
        /// </summary>
        public static string error006 {
            get {
                return ResourceManager.GetString("error006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error: dos o más imágenes para un mismo origen. Función no inyectiva.
        /// </summary>
        public static string error007 {
            get {
                return ResourceManager.GetString("error007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error: tiene que haber al menos dos puntos del color seleccionado en el panel.
        /// </summary>
        public static string error008 {
            get {
                return ResourceManager.GetString("error008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error: la aproximación exponencial no es posible si en el panel existe un punto (eje Y) menor o igual que cero.
        /// </summary>
        public static string error009 {
            get {
                return ResourceManager.GetString("error009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error: la aproximación logarítmica no es posible si en el panel existe un punto (eje X) menor o igual que cero.
        /// </summary>
        public static string error010 {
            get {
                return ResourceManager.GetString("error010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error: el coeficiente ha de ser un número entero positivo mayor que uno.
        /// </summary>
        public static string error011 {
            get {
                return ResourceManager.GetString("error011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error: ya existe un punto con ese color.
        /// </summary>
        public static string error012 {
            get {
                return ResourceManager.GetString("error012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error: la línea.
        /// </summary>
        public static string error013a {
            get {
                return ResourceManager.GetString("error013a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a del fichero de entrada no corresponde con una función.
        /// </summary>
        public static string error013b {
            get {
                return ResourceManager.GetString("error013b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a del fichero de entrada no corresponde con un punto.
        /// </summary>
        public static string error014 {
            get {
                return ResourceManager.GetString("error014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error: no hay funciones para guardar.
        /// </summary>
        public static string error015 {
            get {
                return ResourceManager.GetString("error015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error: no hay funciones para guardar en MenPas.
        /// </summary>
        public static string error016 {
            get {
                return ResourceManager.GetString("error016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha podido realizar la conexión con la plataforma MenPas. Contacte con el administrador.
        /// </summary>
        public static string error017 {
            get {
                return ResourceManager.GetString("error017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en la grabación de funciones de la fila.
        /// </summary>
        public static string error018 {
            get {
                return ResourceManager.GetString("error018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error: no hay puntos para guardar en MenPas.
        /// </summary>
        public static string error019 {
            get {
                return ResourceManager.GetString("error019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en la grabación de puntos de la fila.
        /// </summary>
        public static string error020 {
            get {
                return ResourceManager.GetString("error020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error: no hay puntos para guardar.
        /// </summary>
        public static string error021 {
            get {
                return ResourceManager.GetString("error021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error: la función &quot;f(x)=.
        /// </summary>
        public static string error022a {
            get {
                return ResourceManager.GetString("error022a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &quot; ya se encuentra en el historial.
        /// </summary>
        public static string error022b {
            get {
                return ResourceManager.GetString("error022b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error: el punto.
        /// </summary>
        public static string error023a {
            get {
                return ResourceManager.GetString("error023a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ya se encuentra en el historial.
        /// </summary>
        public static string error023b {
            get {
                return ResourceManager.GetString("error023b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error: no tiene privilegios para borrar las funciones seleccionadas.
        /// </summary>
        public static string error024 {
            get {
                return ResourceManager.GetString("error024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en el borrado de funciones de la fila.
        /// </summary>
        public static string error025 {
            get {
                return ResourceManager.GetString("error025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error: no ha seleccionado ninguna función.
        /// </summary>
        public static string error026 {
            get {
                return ResourceManager.GetString("error026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error: no tiene privilegios para borrar los puntos seleccionados.
        /// </summary>
        public static string error027 {
            get {
                return ResourceManager.GetString("error027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en el borrado de puntos de la fila.
        /// </summary>
        public static string error028 {
            get {
                return ResourceManager.GetString("error028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error: no ha seleccionado ningún punto.
        /// </summary>
        public static string error029 {
            get {
                return ResourceManager.GetString("error029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error: no se puede aumentar más el zoom.
        /// </summary>
        public static string error030 {
            get {
                return ResourceManager.GetString("error030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error: no se puede disminuir más el zoom.
        /// </summary>
        public static string error031 {
            get {
                return ResourceManager.GetString("error031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error: el desplazamiento ha de ser un número entero positivo mayor que cero y múltiplo de 10.
        /// </summary>
        public static string error032 {
            get {
                return ResourceManager.GetString("error032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error: el punto insertado en el eje Y no es un número.
        /// </summary>
        public static string error033 {
            get {
                return ResourceManager.GetString("error033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error: el punto insertado en el eje X no es un número.
        /// </summary>
        public static string error034 {
            get {
                return ResourceManager.GetString("error034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error: debe insertar un número en la coordenada X.
        /// </summary>
        public static string error035 {
            get {
                return ResourceManager.GetString("error035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error: debe insertar un número en la coordenada Y.
        /// </summary>
        public static string error036 {
            get {
                return ResourceManager.GetString("error036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error: el punto insertado en el eje X no es una coordenada.
        /// </summary>
        public static string error037a {
            get {
                return ResourceManager.GetString("error037a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error: el punto insertado en el eje Y no es una coordenada.
        /// </summary>
        public static string error037b {
            get {
                return ResourceManager.GetString("error037b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error: la columna.
        /// </summary>
        public static string error038a {
            get {
                return ResourceManager.GetString("error038a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a no es un número. La importación se ha cancelado.
        /// </summary>
        public static string error038b {
            get {
                return ResourceManager.GetString("error038b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error: existe un error de importación en la función de la columna.
        /// </summary>
        public static string error039 {
            get {
                return ResourceManager.GetString("error039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error: el fichero ha de contener dos o más puntos.
        /// </summary>
        public static string error040 {
            get {
                return ResourceManager.GetString("error040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error: el número de filas ha de ser un número entero positivo mayor o igual que cero.
        /// </summary>
        public static string error041 {
            get {
                return ResourceManager.GetString("error041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a no contiene un punto. Su formato ha de ser &quot;(x, y)&quot;. Dicha columna no va a ser importada.
        /// </summary>
        public static string error042 {
            get {
                return ResourceManager.GetString("error042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dicha columna no va a ser importada.
        /// </summary>
        public static string error043 {
            get {
                return ResourceManager.GetString("error043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a no es un número. Dicha columna no va a ser importada.
        /// </summary>
        public static string error044 {
            get {
                return ResourceManager.GetString("error044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error: existe un error de importación en la nube de la columna.
        /// </summary>
        public static string error045 {
            get {
                return ResourceManager.GetString("error045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Incapaz de lanzar el objeto.
        /// </summary>
        public static string error046 {
            get {
                return ResourceManager.GetString("error046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error: dos o más imágenes para un mismo origen. Función no inyectiva.
        /// </summary>
        public static string error047 {
            get {
                return ResourceManager.GetString("error047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error: tiene que haber al menos dos puntos del color seleccionado en el panel.
        /// </summary>
        public static string error048 {
            get {
                return ResourceManager.GetString("error048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error: seleccione antes un tipo de aproximación.
        /// </summary>
        public static string error049 {
            get {
                return ResourceManager.GetString("error049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error: la aproximación exponencial no es posible si en el panel existe un punto (eje Y) menor o igual que cero.
        /// </summary>
        public static string error050 {
            get {
                return ResourceManager.GetString("error050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error: la aproximación logarítmica no es posible si en el panel existe un punto (eje X) menor o igual que cero.
        /// </summary>
        public static string error051 {
            get {
                return ResourceManager.GetString("error051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error: punto existente en columna.
        /// </summary>
        public static string error052a {
            get {
                return ResourceManager.GetString("error052a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a con coordenadas.
        /// </summary>
        public static string error052b {
            get {
                return ResourceManager.GetString("error052b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Estado de programa.
        /// </summary>
        public static string estadoDePrograma {
            get {
                return ResourceManager.GetString("estadoDePrograma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Evaluación correcta de función.
        /// </summary>
        public static string evaluacionCorrectaDeFuncion {
            get {
                return ResourceManager.GetString("evaluacionCorrectaDeFuncion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Evaluación incorrecta de función.
        /// </summary>
        public static string evaluacionIncorrectaDeFuncion {
            get {
                return ResourceManager.GetString("evaluacionIncorrectaDeFuncion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exportación a Word correcta.
        /// </summary>
        public static string exportacionAWordCorrecta {
            get {
                return ResourceManager.GetString("exportacionAWordCorrecta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Factor de desplazamiento:.
        /// </summary>
        public static string factorDeDesplazamiento {
            get {
                return ResourceManager.GetString("factorDeDesplazamiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a fila.
        /// </summary>
        public static string fila {
            get {
                return ResourceManager.GetString("fila", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de filas para importar.
        /// </summary>
        public static string Filas {
            get {
                return ResourceManager.GetString("Filas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Funcion|*.doc.
        /// </summary>
        public static string funcionDoc {
            get {
                return ResourceManager.GetString("funcionDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a funciones.
        /// </summary>
        public static string funciones {
            get {
                return ResourceManager.GetString("funciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Funciones borradas correctamente.
        /// </summary>
        public static string funcionesBorradasCorrectamente {
            get {
                return ResourceManager.GetString("funcionesBorradasCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Funciones grabadas correctamente.
        /// </summary>
        public static string funcionesGrabadasCorrectamente {
            get {
                return ResourceManager.GetString("funcionesGrabadasCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gris.
        /// </summary>
        public static string gris {
            get {
                return ResourceManager.GetString("gris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar panel.
        /// </summary>
        public static string guardarPanel {
            get {
                return ResourceManager.GetString("guardarPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Historial de funciones guardado correctamente.
        /// </summary>
        public static string historialDeFuncionesGuardadoCorrectamente {
            get {
                return ResourceManager.GetString("historialDeFuncionesGuardadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Historial de puntos guardado correctamente.
        /// </summary>
        public static string historialDePuntosGuardadoCorrectamente {
            get {
                return ResourceManager.GetString("historialDePuntosGuardadoCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Historial funciones|*.txt.
        /// </summary>
        public static string historialFunciones {
            get {
                return ResourceManager.GetString("historialFunciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Historial puntos|*.txt.
        /// </summary>
        public static string historialPuntos {
            get {
                return ResourceManager.GetString("historialPuntos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hoja de funciones|*.xlsx;*.xls.
        /// </summary>
        public static string hojaDeFunciones {
            get {
                return ResourceManager.GetString("hojaDeFunciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importación de función realizada correctamente.
        /// </summary>
        public static string importacionFuncionOK {
            get {
                return ResourceManager.GetString("importacionFuncionOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importar funciones seleccionadas.
        /// </summary>
        public static string importarFunciones {
            get {
                return ResourceManager.GetString("importarFunciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importar nubes de puntos.
        /// </summary>
        public static string importarNubeDePuntos {
            get {
                return ResourceManager.GetString("importarNubeDePuntos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importar puntos seleccionados.
        /// </summary>
        public static string importarPuntos {
            get {
                return ResourceManager.GetString("importarPuntos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importar puntos de Bland y Altman.
        /// </summary>
        public static string importarPuntosBlandYAltman {
            get {
                return ResourceManager.GetString("importarPuntosBlandYAltman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Importar puntos de aplicación Hoisan.
        /// </summary>
        public static string importarPuntosHoisan {
            get {
                return ResourceManager.GetString("importarPuntosHoisan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error: usuario o contraseña incorrecta.
        /// </summary>
        public static string inicioNok {
            get {
                return ResourceManager.GetString("inicioNok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Inicio de sesión correcta.
        /// </summary>
        public static string inicioOk {
            get {
                return ResourceManager.GetString("inicioOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Interpolación polinómica.
        /// </summary>
        public static string interpolacionPolinomica {
            get {
                return ResourceManager.GetString("interpolacionPolinomica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduzca la coordenada X:.
        /// </summary>
        public static string introduzcaCoordenadaX {
            get {
                return ResourceManager.GetString("introduzcaCoordenadaX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Introduzca la coordenada Y:.
        /// </summary>
        public static string introduzcaCoordenadaY {
            get {
                return ResourceManager.GetString("introduzcaCoordenadaY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Magenta.
        /// </summary>
        public static string magenta {
            get {
                return ResourceManager.GetString("magenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Marrón.
        /// </summary>
        public static string marron {
            get {
                return ResourceManager.GetString("marron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Naranja.
        /// </summary>
        public static string naranja {
            get {
                return ResourceManager.GetString("naranja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Negro.
        /// </summary>
        public static string negro {
            get {
                return ResourceManager.GetString("negro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (No hay funciones en el historial).
        /// </summary>
        public static string noHayFuncionesEnElHistorial {
            get {
                return ResourceManager.GetString("noHayFuncionesEnElHistorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a (No hay puntos en el historial).
        /// </summary>
        public static string noHayPuntosEnElHistorial {
            get {
                return ResourceManager.GetString("noHayPuntosEnElHistorial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede aumentar más el zoom.
        /// </summary>
        public static string noSePuedeAumentarMasElZoom {
            get {
                return ResourceManager.GetString("noSePuedeAumentarMasElZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede disminuir más el zoom.
        /// </summary>
        public static string noSePuedeDisminuirMasElZoom {
            get {
                return ResourceManager.GetString("noSePuedeDisminuirMasElZoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a nubes de puntos.
        /// </summary>
        public static string nubesDePuntos {
            get {
                return ResourceManager.GetString("nubesDePuntos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de filas:.
        /// </summary>
        public static string numeroDeFilas {
            get {
                return ResourceManager.GetString("numeroDeFilas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Punto insertado en coordenada.
        /// </summary>
        public static string puntoInsertadoEnCoordenada {
            get {
                return ResourceManager.GetString("puntoInsertadoEnCoordenada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puntos borrados correctamente.
        /// </summary>
        public static string puntosBorradosCorrectamente {
            get {
                return ResourceManager.GetString("puntosBorradosCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puntos grabados correctamente.
        /// </summary>
        public static string puntosGrabadosCorrectamente {
            get {
                return ResourceManager.GetString("puntosGrabadosCorrectamente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puntos.
        /// </summary>
        public static string puntosMayuscula {
            get {
                return ResourceManager.GetString("puntosMayuscula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a puntos.
        /// </summary>
        public static string puntosMinuscula {
            get {
                return ResourceManager.GetString("puntosMinuscula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regresión exponencial.
        /// </summary>
        public static string regresionExponencial {
            get {
                return ResourceManager.GetString("regresionExponencial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regresión lineal.
        /// </summary>
        public static string regresionLineal {
            get {
                return ResourceManager.GetString("regresionLineal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regresión logarítmica.
        /// </summary>
        public static string regresionLogaritmica {
            get {
                return ResourceManager.GetString("regresionLogaritmica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Regresión polinómica.
        /// </summary>
        public static string regresionPolinomica {
            get {
                return ResourceManager.GetString("regresionPolinomica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rojo.
        /// </summary>
        public static string rojo {
            get {
                return ResourceManager.GetString("rojo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se han cargado con éxito un total de.
        /// </summary>
        public static string seHanCargadoConExito {
            get {
                return ResourceManager.GetString("seHanCargadoConExito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se han importado un total de.
        /// </summary>
        public static string seHanImportado {
            get {
                return ResourceManager.GetString("seHanImportado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona una hoja de cálculo a importar.
        /// </summary>
        public static string seleccionaUnaHojaDeCalculo {
            get {
                return ResourceManager.GetString("seleccionaUnaHojaDeCalculo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona un fichero doc a exportar.
        /// </summary>
        public static string seleccionaUnFicheroDoc {
            get {
                return ResourceManager.GetString("seleccionaUnFicheroDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona un historial de funciones.
        /// </summary>
        public static string seleccionaUnHistorialDeFunciones {
            get {
                return ResourceManager.GetString("seleccionaUnHistorialDeFunciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Selecciona un historial de puntos.
        /// </summary>
        public static string seleccionaUnHistorialDePuntos {
            get {
                return ResourceManager.GetString("seleccionaUnHistorialDePuntos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se va a cancelar la importación.
        /// </summary>
        public static string seVaACancelarLaImportacion {
            get {
                return ResourceManager.GetString("seVaACancelarLaImportacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tamaño.
        /// </summary>
        public static string tamaño {
            get {
                return ResourceManager.GetString("tamaño", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo de función.
        /// </summary>
        public static string tipoDeFuncion {
            get {
                return ResourceManager.GetString("tipoDeFuncion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Verde.
        /// </summary>
        public static string verde {
            get {
                return ResourceManager.GetString("verde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Violeta.
        /// </summary>
        public static string violeta {
            get {
                return ResourceManager.GetString("violeta", resourceCulture);
            }
        }
    }
}
